Add controllers
valikaev1989/java-shareit pull request #1
Opened 2022-08-14 13:29 UTC by valikaev1989

2022-08-14 22:22 UTC, kukolev requested changes

2022-08-14 22:22 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +public interface BookingRepository {
Здесь нужна todo с информацией о том, что класс будет реализован в следующих спринтах.

2022-08-14 22:22 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepositoryImpl.java
> +public class BookingRepositoryImpl {
Здесь нужна todo с информацией о том, что класс будет реализован в следующих спринтах.

2022-08-14 22:22 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +public interface BookingService {
Здесь нужна todo с информацией о том, что класс будет реализован в следующих спринтах.

2022-08-14 22:22 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +public class BookingServiceImpl {
Здесь нужна todo с информацией о том, что класс будет реализован в следующих спринтах.

2022-08-14 22:22 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public ItemServiceImpl(ItemMapper itemMapper, ItemRepository itemRepository, UserMapper userMapper, UserService userService) {
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину. Подробнее можно почитать тут: https://www.notion.so/praktikum/Code-guide-Java-d835be24c32d4265aeb4007652f40e6f#8454ceb4e0d6417d985c0418586015f1

2022-08-14 22:22 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private void validateItemNameAndDescAndAvailable(ItemDto itemDto) {
По моему название слишком громоздкое. Лучше сделать название короче.

2022-08-15 17:10 UTC, valikaev1989 commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +public interface BookingRepository {
fix

2022-08-15 17:10 UTC, valikaev1989 commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepositoryImpl.java
> +public class BookingRepositoryImpl {
fix

2022-08-15 17:10 UTC, valikaev1989 commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +public interface BookingService {
fix

2022-08-15 17:10 UTC, valikaev1989 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +public class BookingServiceImpl {
fix

2022-08-15 17:10 UTC, valikaev1989 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public ItemServiceImpl(ItemMapper itemMapper, ItemRepository itemRepository, UserMapper userMapper, UserService userService) {
fix

2022-08-15 17:10 UTC, valikaev1989 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private void validateItemNameAndDescAndAvailable(ItemDto itemDto) {
fix

2022-08-16 06:46 UTC, kukolev requested changes

2022-08-16 06:46 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +/**
Эти комментарии нужно оформить как TODO. Это важно, т.к. современные IDE позволяют быстро находить все TODO, что делает их применение удобней.

2022-08-16 06:46 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepositoryImpl.java
> + * // будет реализовано после 13-го спринта .
Эти комментарии нужно оформить как TODO. Это важно, т.к. современные IDE позволяют быстро находить все TODO, что делает их применение удобней.

2022-08-16 06:46 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> + * // будет реализовано после 13-го спринта .
Эти комментарии нужно оформить как TODO. Это важно, т.к. современные IDE позволяют быстро находить все TODO, что делает их применение удобней.

2022-08-16 06:46 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> + * // будет реализовано после 13-го спринта .
Эти комментарии нужно оформить как TODO. Это важно, т.к. современные IDE позволяют быстро находить все TODO, что делает их применение удобней.

2022-08-16 06:46 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            validateItemName(itemDto);
По моему здесь и ниже лишнее усложнение. Метод validateItemName и так проверяет имя на null. Проще убрать вообще все проверки оставить просто присвоения имени после валидации.

2022-08-16 06:46 UTC, kukolev commented on src/main/java/ru/practicum/shareit/request/repository/ItemRequestRepository.java
> + * // будет реализовано после 13-го спринта .
Эти комментарии нужно оформить как TODO. Это важно, т.к. современные IDE позволяют быстро находить все TODO, что делает их применение удобней.

2022-08-16 06:46 UTC, kukolev commented on src/main/java/ru/practicum/shareit/request/repository/ItemRequestRepositoryImpl.java
> + * // будет реализовано после 13-го спринта .
Эти комментарии нужно оформить как TODO. Это важно, т.к. современные IDE позволяют быстро находить все TODO, что делает их применение удобней.

2022-08-16 06:46 UTC, kukolev commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestService.java
> + * // будет реализовано после 13-го спринта .
Эти комментарии нужно оформить как TODO. Это важно, т.к. современные IDE позволяют быстро находить все TODO, что делает их применение удобней.

2022-08-16 06:46 UTC, kukolev commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> + * // будет реализовано после 13-го спринта .
Эти комментарии нужно оформить как TODO. Это важно, т.к. современные IDE позволяют быстро находить все TODO, что делает их применение удобней.

2022-08-16 06:46 UTC, kukolev commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +        assertThrows(ValidationException.class, () -> itemController.addNewItem(userDto.getId(), item1.toBuilder().name("").build()));
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину. Подробнее можно почитать тут: https://www.notion.so/praktikum/Code-guide-Java-d835be24c32d4265aeb4007652f40e6f#8454ceb4e0d6417d985c0418586015f1

2022-08-16 06:46 UTC, kukolev commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +        assertThrows(ValidationException.class, () -> itemController.addNewItem(userDto.getId(), item1.toBuilder().description("").build()));
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину. Подробнее можно почитать тут: https://www.notion.so/praktikum/Code-guide-Java-d835be24c32d4265aeb4007652f40e6f#8454ceb4e0d6417d985c0418586015f1

2022-08-16 18:10 UTC, valikaev1989 commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +        assertThrows(ValidationException.class, () -> itemController.addNewItem(userDto.getId(), item1.toBuilder().description("").build()));
fix

2022-08-16 18:10 UTC, valikaev1989 commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +        assertThrows(ValidationException.class, () -> itemController.addNewItem(userDto.getId(), item1.toBuilder().name("").build()));
fix

2022-08-16 18:10 UTC, valikaev1989 commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> + * // будет реализовано после 13-го спринта .
fix

2022-08-16 18:11 UTC, valikaev1989 commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestService.java
> + * // будет реализовано после 13-го спринта .
fix

2022-08-16 18:11 UTC, valikaev1989 commented on src/main/java/ru/practicum/shareit/request/repository/ItemRequestRepositoryImpl.java
> + * // будет реализовано после 13-го спринта .
fix

2022-08-16 18:11 UTC, valikaev1989 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            validateItemName(itemDto);
fix

2022-08-16 18:11 UTC, valikaev1989 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> + * // будет реализовано после 13-го спринта .
fix

2022-08-16 18:11 UTC, valikaev1989 commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> + * // будет реализовано после 13-го спринта .
fix

2022-08-16 18:11 UTC, valikaev1989 commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepositoryImpl.java
> + * // будет реализовано после 13-го спринта .
fix

2022-08-16 18:11 UTC, valikaev1989 commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +/**
fix

2022-08-16 22:07 UTC, kukolev requested changes

2022-08-16 22:07 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> + * // TODO .
TODO нужно делать вместе с текстом. В данному случае это может выглядеть примерно так:

`// TODO: будет реализовано после 13-го спринта`

или

`// TODO: Реализовать на 12-м спринте`
 
или еще как-то подобным образом. Важно, чтобы это было TODO и чтобы было понятно, что нужно сделать.

Аналогично нужно поправить в остальных местах.

2022-08-17 15:50 UTC, valikaev1989 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> + * // TODO .
fix

2022-08-17 20:22 UTC, kukolev approved these changes

2022-08-18 15:33 UTC, merged