Add bookings
valikaev1989/java-shareit pull request #2
Opened 2022-09-04 17:13 UTC by valikaev1989

2022-09-04 20:36 UTC, kukolev requested changes

2022-09-04 20:36 UTC, kukolev commented on pom.xml
> +		<dependency>
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-09-04 20:36 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        Booking l = bookingRepository.findFirstByItem_IdOrderByEndDesc(itemId);
Нарушение кодстайла: Переменные должны называться так, чтобы из названия можно было понять, за что отвечает переменная. Так код будет понятней при анализе.

2022-09-04 20:36 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        Booking n = bookingRepository.findFirstByItem_IdOrderByStartAsc(itemId);
Нарушение кодстайла: Переменные должны называться так, чтобы из названия можно было понять, за что отвечает переменная. Так код будет понятней при анализе.

2022-09-04 22:22 UTC, valikaev1989 commented on pom.xml
> +		<dependency>
fix

2022-09-04 22:22 UTC, valikaev1989 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        Booking l = bookingRepository.findFirstByItem_IdOrderByEndDesc(itemId);
fix

2022-09-04 22:22 UTC, valikaev1989 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        Booking n = bookingRepository.findFirstByItem_IdOrderByStartAsc(itemId);
fix

2022-09-05 14:22 UTC, kukolev requested changes

2022-09-05 14:22 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/dto/ItemOwnerDto.java
> +    BookingDtoOnlyId lastBooking;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-09-05 14:22 UTC, kukolev commented on src/main/resources/application.properties
> +#spring.datasource.url=jdbc:postgresql://localhost:5432/shareit
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-09-05 14:22 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    Booking findFirstByItem_IdOrderByEndDesc(long itemId);
Нарушение кодстайла: название методов должно быть выполнено в стиле camelCase.

Аналогично нужно поправить ниже.

2022-09-05 14:22 UTC, kukolev commented on src/main/java/ru/practicum/shareit/util/Validator.java
> +        java.util.regex.Pattern p = java.util.regex.Pattern.compile(ePattern);
Нарушение кодстайла: Переменные должны называться так, чтобы из названия можно было понять, за что отвечает переменная. Так код будет понятней при анализе.

2022-09-05 14:22 UTC, kukolev commented on src/main/java/ru/practicum/shareit/util/Validator.java
> +        java.util.regex.Matcher m = p.matcher(userDto.getEmail());
Нарушение кодстайла: Переменные должны называться так, чтобы из названия можно было понять, за что отвечает переменная. Так код будет понятней при анализе.

2022-09-05 17:21 UTC, valikaev1989 commented on src/main/java/ru/practicum/shareit/item/dto/ItemOwnerDto.java
> +    BookingDtoOnlyId lastBooking;
fix

2022-09-05 17:24 UTC, valikaev1989 commented on src/main/java/ru/practicum/shareit/util/Validator.java
> +        java.util.regex.Pattern p = java.util.regex.Pattern.compile(ePattern);
fix

2022-09-05 17:25 UTC, valikaev1989 commented on src/main/java/ru/practicum/shareit/util/Validator.java
> +        java.util.regex.Matcher m = p.matcher(userDto.getEmail());
fix

2022-09-05 17:38 UTC, valikaev1989 commented on src/main/resources/application.properties
> +#spring.datasource.url=jdbc:postgresql://localhost:5432/shareit
fix

2022-09-05 17:38 UTC, valikaev1989 commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    Booking findFirstByItem_IdOrderByEndDesc(long itemId);
fix

2022-09-06 06:33 UTC, kukolev approved these changes

2022-09-06 16:10 UTC, merged