Add item requests
valikaev1989/java-shareit pull request #5
Opened 2022-09-20 21:01 UTC by valikaev1989

2022-09-21 16:07 UTC, kukolev requested changes

2022-09-21 16:07 UTC, kukolev commented on src/main/java/ru/practicum/shareit/util/Validator.java
> +            log.warn("Вы не владелец вещи");
При логировании лучше добавлять информацию о текущих значениях параметров, чтобы при анализе было понятно о чем идет речь. Здесь будет полезно добавить значение переменный owner и bookingId.

2022-09-21 16:07 UTC, kukolev commented on src/test/java/ru/practicum/shareit/ValidatorTests.java
> +    void validateUserDTO() {
Этот тест лучше разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Так будет проще понять что пошло не так, если один или несколько тестов упадут.

2022-09-21 16:07 UTC, kukolev commented on src/test/java/ru/practicum/shareit/ValidatorTests.java
> +    void validateItemAll() {
Этот тест лучше разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Так будет проще понять что пошло не так, если один или несколько тестов упадут.

2022-09-21 16:07 UTC, kukolev commented on src/test/java/ru/practicum/shareit/ValidatorTests.java
> +    void validateAndReturnItemByItemId() {
Этот тест лучше разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Так будет проще понять что пошло не так, если один или несколько тестов упадут.

2022-09-21 16:07 UTC, kukolev commented on src/test/java/ru/practicum/shareit/ValidatorTests.java
> +    void validateForAddBooking() {
Этот тест лучше разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Так будет проще понять что пошло не так, если один или несколько тестов упадут.

2022-09-21 16:07 UTC, kukolev commented on src/test/java/ru/practicum/shareit/ValidatorTests.java
> +    void validateForGetBooking() {
Этот тест лучше разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Так будет проще понять что пошло не так, если один или несколько тестов упадут.

2022-09-21 16:07 UTC, kukolev commented on src/test/java/ru/practicum/shareit/ValidatorTests.java
> +    void validateForUpdateBooking() {
Этот тест лучше разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Так будет проще понять что пошло не так, если один или несколько тестов упадут.

2022-09-21 16:07 UTC, kukolev commented on src/test/java/ru/practicum/shareit/ValidatorTests.java
> +    void validateAndReturnItemRequestByRequestId() {
Этот тест лучше разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Так будет проще понять что пошло не так, если один или несколько тестов упадут.

2022-09-21 16:07 UTC, kukolev commented on src/test/java/ru/practicum/shareit/bookingTests/BookingIntegrationTests.java
> +    BookingDtoOnlyId bookingDtoOnlyId1 = createBookingForComment();
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-09-21 16:07 UTC, kukolev commented on src/test/java/ru/practicum/shareit/bookingTests/BookingIntegrationTests.java
> +    void addBooking() {
Этот тест лучше разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Так будет проще понять что пошло не так, если один или несколько тестов упадут.

2022-09-21 16:07 UTC, kukolev commented on src/test/java/ru/practicum/shareit/bookingTests/BookingRepositoryTests.java
> +    void getLastNextBooking() {
Этот тест лучше разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Так будет проще понять что пошло не так, если один или несколько тестов упадут.

2022-09-21 16:07 UTC, kukolev commented on src/test/java/ru/practicum/shareit/bookingTests/BookingRepositoryTests.java
> +    void validateForTakeItem() {
Этот тест лучше разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Так будет проще понять что пошло не так, если один или несколько тестов упадут.

2022-09-21 16:07 UTC, kukolev commented on src/test/java/ru/practicum/shareit/itemRequestsTests/ItemRequestControllerTests.java
> +    ItemRequestService itemRequestService;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-09-21 16:07 UTC, kukolev commented on src/test/java/ru/practicum/shareit/itemsTests/ItemServiceTests.java
> +    void addItem() {
Этот тест лучше разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Так будет проще понять что пошло не так, если один или несколько тестов упадут.

2022-09-21 16:07 UTC, kukolev commented on src/test/java/ru/practicum/shareit/itemsTests/ItemServiceTests.java
> +    void findItemOwnerDtoById() {
Этот тест лучше разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Так будет проще понять что пошло не так, если один или несколько тестов упадут.

2022-09-21 16:07 UTC, kukolev commented on src/test/java/ru/practicum/shareit/usersTests/UserServiceTests.java
> +    UserServiceImpl mockUserService;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-09-21 16:17 UTC, valikaev1989 commented on src/test/java/ru/practicum/shareit/usersTests/UserServiceTests.java
> +    UserServiceImpl mockUserService;
fix

2022-09-21 16:20 UTC, valikaev1989 commented on src/test/java/ru/practicum/shareit/itemRequestsTests/ItemRequestControllerTests.java
> +    ItemRequestService itemRequestService;
fix

2022-09-21 16:21 UTC, valikaev1989 commented on src/test/java/ru/practicum/shareit/bookingTests/BookingIntegrationTests.java
> +    BookingDtoOnlyId bookingDtoOnlyId1 = createBookingForComment();
fix

2022-09-21 16:35 UTC, valikaev1989 commented on src/main/java/ru/practicum/shareit/util/Validator.java
> +            log.warn("Вы не владелец вещи");
fix

2022-09-21 16:39 UTC, valikaev1989 commented on src/test/java/ru/practicum/shareit/ValidatorTests.java
> +    void validateUserDTO() {
fix

2022-09-21 16:43 UTC, valikaev1989 commented on src/test/java/ru/practicum/shareit/ValidatorTests.java
> +    void validateItemAll() {
fix

2022-09-21 17:50 UTC, valikaev1989 commented on src/test/java/ru/practicum/shareit/ValidatorTests.java
> +    void validateAndReturnItemByItemId() {
fix

2022-09-21 18:12 UTC, valikaev1989 commented on src/test/java/ru/practicum/shareit/ValidatorTests.java
> +    void validateForAddBooking() {
fix

2022-09-21 18:31 UTC, valikaev1989 commented on src/test/java/ru/practicum/shareit/ValidatorTests.java
> +    void validateForGetBooking() {
fix

2022-09-21 18:45 UTC, valikaev1989 commented on src/test/java/ru/practicum/shareit/ValidatorTests.java
> +    void validateForUpdateBooking() {
fix

2022-09-21 18:52 UTC, valikaev1989 commented on src/test/java/ru/practicum/shareit/ValidatorTests.java
> +    void validateAndReturnItemRequestByRequestId() {
fix

2022-09-21 18:57 UTC, valikaev1989 commented on src/test/java/ru/practicum/shareit/bookingTests/BookingIntegrationTests.java
> +    void addBooking() {
fix

2022-09-21 19:31 UTC, valikaev1989 commented on src/test/java/ru/practicum/shareit/bookingTests/BookingRepositoryTests.java
> +    void getLastNextBooking() {
fix

2022-09-21 20:00 UTC, valikaev1989 commented on src/test/java/ru/practicum/shareit/bookingTests/BookingRepositoryTests.java
> +    void validateForTakeItem() {
fix

2022-09-21 20:16 UTC, valikaev1989 commented on src/test/java/ru/practicum/shareit/itemsTests/ItemServiceTests.java
> +    void addItem() {
тут один тест был. нечего разбивать

2022-09-21 20:16 UTC, valikaev1989 commented on src/test/java/ru/practicum/shareit/itemsTests/ItemServiceTests.java
> +    void findItemOwnerDtoById() {
fix

2022-09-22 20:04 UTC, kukolev requested changes

2022-09-22 20:04 UTC, kukolev commented on src/test/java/ru/practicum/shareit/itemsTests/ItemServiceTests.java
> +    void addItem() {
Да верно, наверное я промахнулся. Нужно было отметить верхний тест - void findItemsByText(). Его точно нужно разбить на два, т.к. сервис вызывается два раза.

2022-09-22 20:04 UTC, kukolev commented on src/test/java/ru/practicum/shareit/itemsTests/ItemServiceTests.java
> +    void findItemsByText() {
Этот тест лучше разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Так будет проще понять что пошло не так, если один или несколько тестов упадут.

2022-09-23 17:09 UTC, kukolev approved these changes

2022-09-24 16:20 UTC, merged