Add docker
valikaev1989/java-shareit pull request #6
Opened 2022-09-30 22:57 UTC by valikaev1989

2022-10-02 08:24 UTC, kukolev requested changes

2022-10-02 08:24 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        validator.validateId(userId);
Бизнес-логика должна быть реализована в сервисах, а не в контроллере. Именно сервис инкапсулирует всю логику работы приложения и выставляет наружу методы, которые потом вызываются из контроллеров или из других сервисов.

Аналогично нужно поправить ниже.

2022-10-02 08:24 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +        validator.validateId(userId);
Бизнес-логика должна быть реализована в сервисах, а не в контроллере. Именно сервис инкапсулирует всю логику работы приложения и выставляет наружу методы, которые потом вызываются из контроллеров или из других сервисов.

Аналогично нужно поправить ниже.

2022-10-02 08:24 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/request/RequestController.java
> +        validator.validateId(userId);
Бизнес-логика должна быть реализована в сервисах, а не в контроллере. Именно сервис инкапсулирует всю логику работы приложения и выставляет наружу методы, которые потом вызываются из контроллеров или из других сервисов.

Аналогично нужно поправить ниже.

2022-10-02 08:24 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/user/UserController.java
> +        validator.validateUserDTO(userDto);
Бизнес-логика должна быть реализована в сервисах, а не в контроллере. Именно сервис инкапсулирует всю логику работы приложения и выставляет наружу методы, которые потом вызываются из контроллеров или из других сервисов.

Аналогично нужно поправить ниже.

2022-10-02 08:24 UTC, kukolev commented on gateway/src/main/resources/application.properties
> +#logging.level.org.apache.http=DEBUG
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-10-02 08:24 UTC, kukolev commented on server/pom.xml
> +	<modelVersion>4.0.0</modelVersion>
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-10-02 08:24 UTC, kukolev commented on server/src/main/java/ru/practicum/shareit/ShareItServer.java
> +	public static void main(String[] args) {
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-10-02 08:24 UTC, kukolev commented on server/src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +//        validator.validateItemAll(itemDto);
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-10-02 08:24 UTC, kukolev commented on server/src/main/java/ru/practicum/shareit/util/ValidatorServer.java
> +    public void validateEmailUser(UserDto userDto) {
Не выполнено требование ТЗ: Вынести в shareIt-gateway всю логику валидации входных данных — кроме той, которая требует работы с БД. Необходимо вынести валидацию входных данных в shareIt-gateway.

2022-10-02 08:24 UTC, kukolev commented on server/src/test/java/ru/practicum/shareit/bookingTests/BookingServiceTests.java
> +//    @Test
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-10-02 08:24 UTC, kukolev commented on server/src/test/java/ru/practicum/shareit/bookingTests/BookingServiceTests.java
> +//    @Test
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-10-02 09:40 UTC, valikaev1989 commented on server/src/test/java/ru/practicum/shareit/bookingTests/BookingServiceTests.java
> +//    @Test
fix

2022-10-02 09:41 UTC, valikaev1989 commented on server/src/test/java/ru/practicum/shareit/bookingTests/BookingServiceTests.java
> +//    @Test
fix

2022-10-02 09:46 UTC, valikaev1989 commented on server/src/main/java/ru/practicum/shareit/util/ValidatorServer.java
> +    public void validateEmailUser(UserDto userDto) {
fix

2022-10-02 09:47 UTC, valikaev1989 commented on server/src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +//        validator.validateItemAll(itemDto);
fix

2022-10-02 09:48 UTC, valikaev1989 commented on server/src/main/java/ru/practicum/shareit/ShareItServer.java
> +	public static void main(String[] args) {
fix

2022-10-02 09:49 UTC, valikaev1989 commented on gateway/src/main/resources/application.properties
> +#logging.level.org.apache.http=DEBUG
fix

2022-10-02 10:16 UTC, valikaev1989 commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +        validator.validateId(userId);
fix

2022-10-02 10:16 UTC, valikaev1989 commented on gateway/src/main/java/ru/practicum/shareit/request/RequestController.java
> +        validator.validateId(userId);
fix

2022-10-02 10:16 UTC, valikaev1989 commented on gateway/src/main/java/ru/practicum/shareit/user/UserController.java
> +        validator.validateUserDTO(userDto);
fix

2022-10-02 10:16 UTC, valikaev1989 commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        validator.validateId(userId);
fix

2022-10-02 10:26 UTC, valikaev1989 commented on server/pom.xml
> +	<modelVersion>4.0.0</modelVersion>
fix

2022-10-03 08:24 UTC, kukolev requested changes

2022-10-03 08:24 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +    public BookingClient(@Value("${shareit-server.url}") String serverUrl, RestTemplateBuilder builder, ValidatorGateway validator) {
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-10-03 08:24 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/util/ValidatorGateway.java
> +    public void validateNameUser(UserDto userDto) {
Метод нужно сделать приватным, т.к. он является вспомогательными и не нужно, чтобы к нему был доступ извне.

2022-10-03 08:24 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/util/ValidatorGateway.java
> +    public void validateNotNullEmailUser(UserDto userDto) {
Метод нужно сделать приватным, т.к. он является вспомогательными и не нужно, чтобы к нему был доступ извне.

2022-10-03 08:24 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/util/ValidatorGateway.java
> +    public void validateItemNotNull(ItemDto itemDto) {
Метод нужно сделать приватным, т.к. он является вспомогательными и не нужно, чтобы к нему был доступ извне.

2022-10-03 08:24 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/util/ValidatorGateway.java
> +    public void validateItemName(ItemDto itemDto) {
Метод нужно сделать приватным, т.к. он является вспомогательными и не нужно, чтобы к нему был доступ извне.

2022-10-03 08:24 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/util/ValidatorGateway.java
> +    public void validateItemDesc(ItemDto itemDto) {
Метод нужно сделать приватным, т.к. он является вспомогательными и не нужно, чтобы к нему был доступ извне.

2022-10-03 15:42 UTC, valikaev1989 commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +    public BookingClient(@Value("${shareit-server.url}") String serverUrl, RestTemplateBuilder builder, ValidatorGateway validator) {
fixed

2022-10-03 15:43 UTC, valikaev1989 commented on gateway/src/main/java/ru/practicum/shareit/util/ValidatorGateway.java
> +    public void validateNameUser(UserDto userDto) {
fixed

2022-10-03 15:43 UTC, valikaev1989 commented on gateway/src/main/java/ru/practicum/shareit/util/ValidatorGateway.java
> +    public void validateNotNullEmailUser(UserDto userDto) {
fixed

2022-10-03 15:45 UTC, valikaev1989 commented on gateway/src/main/java/ru/practicum/shareit/util/ValidatorGateway.java
> +    public void validateItemNotNull(ItemDto itemDto) {
fixed

2022-10-03 15:46 UTC, valikaev1989 commented on gateway/src/main/java/ru/practicum/shareit/util/ValidatorGateway.java
> +    public void validateItemName(ItemDto itemDto) {
fixed

2022-10-03 15:46 UTC, valikaev1989 commented on gateway/src/main/java/ru/practicum/shareit/util/ValidatorGateway.java
> +    public void validateItemDesc(ItemDto itemDto) {
fixed

2022-10-04 08:10 UTC, kukolev approved these changes

2022-10-04 08:12 UTC, merged